--- #YAML:1.0
name:                DBIx-Dictionary
version:             0.01
abstract:            Support for query dictionaries in DBI
license:             ~
author:              
    - Igor Sutton <izut@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::General:               2.37
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
